name: grizzly_nlp
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: teja <email@example.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  grizzly_array:
    path: ../grizzly_array
  grizzly_primitives:
    path: ../grizzly_primitives
